
Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox"

  config.vm.provider "virtualbox" do |vb|
  end

  config.vm.box = "bento/centos-7.1"
  config.vm.network "private_network", ip: "55.55.55.150"

end
