version: '2.2'
services:
  node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: node-1
    environment:
      - node.name=node-1
      - cluster.name=tarzan-cluster
      - discovery.seed_hosts=node-2,node-3
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: node-2
    environment:
      - node.name=node-2
      - cluster.name=tarzan-cluster
      - discovery.seed_hosts=node-1,node-3
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-2:/usr/share/elasticsearch/data
    networks:
      - elastic
  node-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: node-3
    environment:
      - node.name=node-3
      - cluster.name=tarzan-cluster
      - discovery.seed_hosts=node-1,node-2
      - cluster.initial_master_nodes=node-1,node-2,node-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-3:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://node-1:9200
      ELASTICSEARCH_HOSTS: '["http://node-1:9200","http://node-2:9200","http://node-3:9200"]'
    networks:
      - elastic      

volumes:
  data-1:
    driver: local
  data-2:
    driver: local
  data-3:
    driver: local

networks:
  elastic:
    driver: bridge