---
- hosts: all
  become: yes
  become_user: root
  
  tasks:
  - name: Download Java8 RPM package
    command: "wget  --header 'Cookie: oraclelicense=accept-securebackup-cookie'  http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.rpm"

  - name: Install Java8 RPM package
    command: "rpm -ivh jdk-8u171-linux-x64.rpm"

  - name: Verify Java8 version
    command: "java -version"

  - name: Download Jenkins2
    get_url: url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war dest=/home/vagrant/jenkins.war

  - name: Run Jenkins
    shell:  nohup java -jar /home/vagrant/jenkins.war 2>/dev/null &
