global:
  scrape_interval:     15s 
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
rule_files:
  # - "first_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'app-poc'
    scrape_interval: 1m
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']    

  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']
