Vagrant.configure("2") do |config|

  config.vm.box = 'ubuntu/xenial64'
  
  config.ssh.forward_agent = true
  #config.ssh.username = "ubuntu" # don't need anymore, username 'vagrant' would be used by default, see https://github.com/hashicorp/vagrant/issues/9416
  config.vm.hostname = "dotnetcore.vm"
  config.vm.synced_folder "./src", "/home/vagrant/src"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  # Fix for: "stdin: is not a tty"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = %{bash -c 'BASH_ENV=/etc/profile exec bash'}

  config.vm.network :forwarded_port, guest: 5000, host: 8080
  config.vm.network :private_network, ip: "192.168.68.8"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    locale-gen en_US.UTF-8
    dpkg-reconfigure locales
	wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
	sudo dpkg -i packages-microsoft-prod.deb
	sudo apt-get install apt-transport-https -y
	sudo apt-get update -y
  sudo apt-get install dotnet-sdk-2.2 -y
  SHELL

end