
- name: download cassandra 3.x
  get_url:
    url: https://archive.apache.org/dist/cassandra/{{cassandra_3x_version}}/apache-cassandra-{{cassandra_3x_version}}-bin.tar.gz
    dest: /tmp/apache-cassandra-{{cassandra_3x_version}}-bin.tar.gz
    validate_certs: False

- name: untar cassandra
  command: tar -xzvf /tmp/apache-cassandra-{{cassandra_3x_version}}-bin.tar.gz -C /tmp/

- name: move cassandra files
  command: mv /tmp/apache-cassandra-{{cassandra_3x_version}} /opt/cassandra
  become: yes
  become_user: root

- name: setting permission
  command: chmod -R 777 /opt/cassandra/
  become: yes
  become_user: root

- name: copy cassandra.yml
  copy:
    src: opt/cassandra/conf/cassandra.yaml
    dest: /opt/cassandra/conf/cassandra.yaml

- name: adding the path in the bashrc files
  lineinfile: dest=/root/.bashrc line='export PATH=$PATH:/opt/cassandra/bin' insertafter='EOF' regexp='export PATH=\$PATH:/opt/cassandra/bin' state=present
  become: yes
  become_user: root

- name: source the bashrc file
  shell: source /root/.bashrc
  become: yes
  become_user: root

- name: create service directories
  file:
    path: "/var/log/cassandra"
    state: directory
    owner: vagrant
    group: vagrant

- name: create service directories
  file:
    path: "/var/log/cassandra/cassandra.log"
    state: touch
    owner: vagrant
    group: vagrant

- name: create scripts Directory
  shell: mkdir /opt/cassandra/scripts/

- name: copy config_cass
  copy:
    src: opt/cassandra/scripts/config_cass.sh
    dest: /opt/cassandra/scripts/config_cass.sh

- name: setting executable permissions
  shell: chmod +x /opt/cassandra/scripts/config_cass.sh

- name: run config_cass.sh
  shell: sh /opt/cassandra/scripts/config_cass.sh {{listen_address}}

- name: run cassandra
  shell: "(nohup /opt/cassandra/bin/cassandra -f >> /var/log/cassandra/cassandra.log &)"
  become: yes
  become_user: vagrant
