  - name: Install a repository of packages
    yum:
      name:
        - https://mirror.webtatic.com/yum/el7/epel-release.rpm
        - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
      state: present      

  - name: Install PHP 5.6
    yum: 
      name:
        - php56w 
        - php56w-opcache 
        - php56w-xml 
        - php56w-mcrypt 
        - php56w-gd 
        - php56w-devel 
        - php56w-mysql 
        - php56w-intl 
        - php56w-mbstring
      state: present
