

version: '3.9'

services:

  kong-postgres:
    image: postgres:9.6
    container_name: kong-postgres
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: "kong:latest"
    container_name: kong-migrations 
    command: kong migrations bootstrap
    depends_on:
      - kong-postgres
    environment:
      KONG_PG_HOST: kong-postgres
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    restart: on-failure
 
  kong-gateway:
    image: kong:latest
    container_name: kong-gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      
      KONG_ADMIN_LISTEN: "0.0.0.0:8001,0.0.0.0:8444"
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "0.0.0.0:8443:8443/tcp"

      # ADMIN ports
      - "0.0.0.0:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
    networks:
      - kong-net 
    depends_on:
      - kong-postgres
      - kong-migrations

networks:
  kong-net: 
    external: false