
Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "172.17.177.101"

    node1.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        folder_name: "hello"
      }
    end

  end

end
