imports:
  - path: instance.jinja

resources:
- name: marcelo-instance-poc
  type: instance.jinja
  properties:
    machineType: n1-standard-1 # Sets the 'machineType' template property
    zone: us-central1-a # Sets the 'zone' template property
    network: default # Sets the 'network' template property
    tags:
      - http
