Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.network "private_network", ip: "172.17.177.101"
  config.vm.network "forwarded_port", guest: 9042, host: 9042
  config.vm.network "forwarded_port", guest: 9160, host: 9160
  config.vm.network "forwarded_port", guest: 7199, host: 7199

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
