Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.define "node1" do |machine|
    machine.vm.network "private_network", ip: "172.17.177.21"
  end

  config.vm.define 'controller' do |machine|
    machine.vm.network "private_network", ip: "172.17.177.11"

    machine.vm.provision :ansible_local do |ansible|
      #ansible.host_key_checking = false
      ansible.playbook       = "playbook.yml"
      #ansible.verbose       = '-vvvv'
      ansible.install        = true
      ansible.sudo           = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "inventory"
    end
  end

end
