Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "172.17.177.21"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      # ansible.verbose  = true
    end
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  
  end
  