version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: marceloserpa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mypoc

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080