- name: install unzip
  yum:
    name: unzip
  become: yes
  become_user: root

- name: install artifactory
  get_url:
    url: https://bintray.com/jfrog/artifactory/download_file?file_path=jfrog-artifactory-oss-6.0.2.zip
    dest: /opt/jfrog-artifactory-oss-6.0.2.zip

- name: unzip artifactory
  command: unzip /opt/jfrog-artifactory-oss-6.0.2.zip -d /opt/

- name: rm jfrog-artifactory-oss-6.0.2.zip
  command: rm /opt/jfrog-artifactory-oss-6.0.2.zip

- name: copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
     - { src: 'storage.properties', dest: '/opt/artifactory-oss-6.0.2/etc/storage.properties' }
     - { src: 'artifactory.default', dest: '/opt/artifactory-oss-6.0.2/bin/artifactory.default' }

- name: download jdbc postgresql jar
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-42.2.0.jre6.jar
    dest: /opt/artifactory-oss-6.0.2/tomcat/lib/postgresql-42.2.0.jre6.jars

- name: configure permissions tomcat/conf g+r
  file:
    path: /opt/artifactory-oss-6.0.2/tomcat/conf/
    mode: g+r
    recurse: yes

- name: configure own vagrant
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    mode: 0750
    recurse: yes
  become: yes
  with_items:
    - /opt/artifactory-oss-6.0.2/tomcat/work/
    - /opt/artifactory-oss-6.0.2/tomcat/temp/
    - /opt/artifactory-oss-6.0.2/logs/

- name: install service
  command: /opt/artifactory-oss-6.0.2/bin/installService.sh
  become: true
  become_user: root

- name: start service artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
